lib: [
  "_build/install/default/lib/CamlGame/META"
  "_build/install/default/lib/CamlGame/camel.ml"
  "_build/install/default/lib/CamlGame/camel.mli"
  "_build/install/default/lib/CamlGame/camlGame.a"
  "_build/install/default/lib/CamlGame/camlGame.cma"
  "_build/install/default/lib/CamlGame/camlGame.cmi"
  "_build/install/default/lib/CamlGame/camlGame.cmt"
  "_build/install/default/lib/CamlGame/camlGame.cmx"
  "_build/install/default/lib/CamlGame/camlGame.cmxa"
  "_build/install/default/lib/CamlGame/camlGame.ml"
  "_build/install/default/lib/CamlGame/camlGame__Camel.cmi"
  "_build/install/default/lib/CamlGame/camlGame__Camel.cmt"
  "_build/install/default/lib/CamlGame/camlGame__Camel.cmti"
  "_build/install/default/lib/CamlGame/camlGame__Camel.cmx"
  "_build/install/default/lib/CamlGame/dune-package"
  "_build/install/default/lib/CamlGame/opam"
]
libexec: [
  "_build/install/default/lib/CamlGame/camlGame.cmxs"
]
doc: [
  "_build/install/default/doc/CamlGame/README.md"
]
